name: rcm_flagship
version: "1.0.0"
config-version: 2

profile: rcm_flagship

model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rcm_flagship:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
    ml:
      +materialized: view
